source "https://rubygems.org"

gem "librarian-puppet", "~> 2.2.3"
gem "puppet",           "~> 4.4"

# Use a legacy Capistrano version, because of its copy strategy.
gem "capistrano",       "~> 2.15.0"
