#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

# use dependencies defined in Modulefile
# modulefile

# A module from git
mod "puppetlabs-postgresql",
  git: "git@github.com:puppetlabs/puppetlabs-postgresql.git",
  ref: "3.4.1"

mod "danzilio-letsencrypt"
